// ═══════════════════════════════════════
// config.js — Constantes e dados iniciais
// ═══════════════════════════════════════

export const ADMIN_PASSWORD = 'onze2025';
export const DATA_FILE      = 'dados.json';
export const GH_REPO_DEFAULT = 'onze-inventario-ti';
export const PARTS = ['Tela','Carcaça','Bateria','Placa','Teclado','SSD','RAM'];
export const PER_PAGE = 50;

export const STATUS_OPTIONS = ['Em uso','Estoque','Canibalização','Sucata','Não definido'];
export const FAB_OPTIONS    = ['APPLE','LENOVO','DELL','OUTRO'];
export const HIST_TYPES     = [
  { value: 'user',   label: '👤 Troca usuário' },
  { value: 'repair', label: '🔧 Conserto' },
  { value: 'note',   label: '📝 Observação' },
  { value: 'cani',   label: '♻️ Canibaliz.' },
];

export const CHART_COLORS = [
  '#0D2137','#163554','#2ABFBF','#22A0A0','#D4AC0D',
  '#2980B9','#E67E22','#E74C3C',
];

export const STATUS_CLASS = {
  'Em uso':       'b-uso',
  'Estoque':      'b-est',
  'Canibalização':'b-can',
  'Sucata':       'b-suc',
};

export const SEED_DATA = [
  {"nome":"SPARE - DEFEITO NÃO LIGA","fabricante":"APPLE","modelo":"MACBOOK PRO 13 (2021)","sn":"C02F96KQML7H","ativo":"353","status":"Estoque","avariado":"Sim","obs":"NÃO LIGA","vendor":"APPLE","nf":"5485288","data":"3/30/2021","valor":"","carregador":"354","garantia":"","old_user":"MAURICIO BUENO","formatado":"","cargo":""},
  {"nome":"SPARE ONZE","fabricante":"APPLE","modelo":"MACBOOK PRO 13","sn":"C02FL88RML7H","ativo":"98","status":"Estoque","avariado":"Não","obs":"","vendor":"ALLIED","nf":"220206","data":"2021-05-08","valor":"","carregador":"99","garantia":"","old_user":"-","formatado":"","cargo":""},
  {"nome":"TARCILA PAULA DA SILVA","fabricante":"LENOVO","modelo":"THINKPAD T490","sn":"PE05P59R","ativo":"337","status":"Não definido","avariado":"Não","obs":"","vendor":"LENOVO","nf":"158922","data":"3/28/2020","valor":"6749.25","carregador":"263","garantia":"","old_user":"AE NOK","formatado":"","cargo":""},
  {"nome":"GESLEY HENRIQUE FLORENTINO","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE07R467","ativo":"281","status":"Não definido","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"9302","data":"8/16/2021","valor":"7.884,00","carregador":"","garantia":"","old_user":"-","formatado":"","cargo":""},
  {"nome":"ANA PAULA NETTO","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE07R46M","ativo":"28","status":"Não definido","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"9302","data":"8/16/2021","valor":"7.884,00","carregador":"33","garantia":"","old_user":"NOVO","formatado":"","cargo":""},
  {"nome":"FELIPE CALLIO","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"FVWFPKXTDH","ativo":"206","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"580432","data":"18/06/2024","valor":"13.569,54","carregador":"207","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":"Engenharia"},
  {"nome":"THAMIRIS MATSUMOTO","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE08S2GW","ativo":"166","status":"Em uso","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"12694","data":"4/26/2022","valor":"","carregador":"167","garantia":"","old_user":"ANGELA GUTIERRES GOMES PAULO","formatado":"","cargo":""},
  {"nome":"CARINE PRA","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"MWNL2XN6MD","ativo":"208","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"580432","data":"18/06/2024","valor":"13.569,54","carregador":"348","garantia":"","old_user":"Giovanni Bernini","formatado":"Sim","cargo":"Produto"},
  {"nome":"GUSTAVO LORONHA","fabricante":"LENOVO","modelo":"THINKPAD T490","sn":"PE065JQE","ativo":"69","status":"Não definido","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"6250","data":"12/17/2020","valor":"","carregador":"70","garantia":"","old_user":"ARIANE CRISTINE DESTRO RAMAZOTTI","formatado":"","cargo":""},
  {"nome":"AUDREY RUTKOSKI","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE08S1E3","ativo":"184","status":"Não definido","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"12694","data":"4/26/2022","valor":"","carregador":"185","garantia":"","old_user":"novo","formatado":"","cargo":""},
  {"nome":"RONALDO ORBITE","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"FK26YWW1Q2","ativo":"228","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"580432","data":"18/06/2024","valor":"13.569,54","carregador":"229","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"SPARE LENOVO T490","fabricante":"LENOVO","modelo":"THINKPAD T490","sn":"PE05ZM0L","ativo":"47931","status":"Não definido","avariado":"Não","obs":"","vendor":"LENOVO","nf":"176103","data":"6/23/2020","valor":"8458.2","carregador":"47932","garantia":"","old_user":"BERNARDO KESSIN PENTEADO","formatado":"","cargo":""},
  {"nome":"SPARE APPLE 2020","fabricante":"APPLE","modelo":"MACBOOK PRO 13 (2020)","sn":"C17D331UML7H","ativo":"319","status":"Estoque","avariado":"Não","obs":"","vendor":"Fastshop","nf":"","data":"8/28/2020","valor":"","carregador":"","garantia":"","old_user":"Alana Oliveira","formatado":"","cargo":""},
  {"nome":"SPARE ONZE MBP","fabricante":"APPLE","modelo":"MACBOOK PRO 13","sn":"C02FL5PLML7H","ativo":"92","status":"Estoque","avariado":"Não","obs":"","vendor":"ALLIED","nf":"269163","data":"2021-07-06","valor":"","carregador":"93","garantia":"","old_user":"BRENDA CRISTINA DEZIO","formatado":"Não","cargo":""},
  {"nome":"SPARE T490 CANI","fabricante":"LENOVO","modelo":"THINKPAD T490","sn":"PE065JLL","ativo":"57273","status":"Canibalização","avariado":"Sim","obs":"RETIRADA AS PEÇAS PARA OUTRAS MAQUINAS","vendor":"DIGITAL WORK","nf":"6250","data":"12/17/2020","valor":"5.970,00","carregador":"57274","garantia":"","old_user":"BRUNA CARDOSO CHAVES","formatado":"","cargo":""},
  {"nome":"BARBARA MIRANDA","fabricante":"LENOVO","modelo":"THINKPAD T490 (2020)","sn":"PE06DSE2","ativo":"260","status":"Não definido","avariado":"Não","obs":"","vendor":"LENOVO","nf":"203057","data":"10/16/2020","valor":"8.690,52","carregador":"57131","garantia":"","old_user":"BRUNO CARVALHO GIAROLA","formatado":"","cargo":""},
  {"nome":"VINICIUS SILVA","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"FF9Y6RM92N","ativo":"210","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"580432","data":"18/06/2024","valor":"13.569,54","carregador":"211","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"ADRIANO LOCHE","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"FW7D64QTW6","ativo":"212","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"580432","data":"18/06/2024","valor":"13.569,54","carregador":"213","garantia":"","old_user":"LUANA BRAUN","formatado":"Sim","cargo":"Financeiro"},
  {"nome":"BIANCA OLIVEIRA","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"FQ5C7GVCC","ativo":"216","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"580432","data":"18/06/2024","valor":"13.569,54","carregador":"215","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"LUCAS DANIEL","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"FNW703Y7DT","ativo":"217","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"580432","data":"18/06/2024","valor":"13.569,54","carregador":"218","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"GABRIELA CALDAS","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"FYKX7K23FC","ativo":"230","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"580432","data":"18/06/2024","valor":"","carregador":"231","garantia":"","old_user":"NOVO","formatado":"","cargo":""},
  {"nome":"VINICIUS VAZ","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"HQCN69VJJK","ativo":"344","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"24052","data":"","valor":"","carregador":"345","garantia":"","old_user":"","formatado":"","cargo":""},
  {"nome":"Guilherme Anguiano","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"GVJJ64JYQ5","ativo":"320","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"24052","data":"","valor":"","carregador":"321","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"FABIO DEBIAZZI OREFICE","fabricante":"LENOVO","modelo":"THINKPAD T490","sn":"PE064R14","ativo":"161","status":"Não definido","avariado":"Não","obs":"","vendor":"LENOVO","nf":"183897","data":"2020-06-08","valor":"7612.41","carregador":"253","garantia":"","old_user":"Leone Bertozo","formatado":"","cargo":""},
  {"nome":"FERNANDA CARVALHO CORTEZ","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE07R463","ativo":"62","status":"Não definido","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"9302","data":"8/16/2021","valor":"7.884,00","carregador":"61","garantia":"","old_user":"novo","formatado":"","cargo":""},
  {"nome":"HENRIQUE NOGUEIRA","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"GY2MQDQ7JC","ativo":"346","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"24052","data":"","valor":"","carregador":"347","garantia":"","old_user":"","formatado":"","cargo":""},
  {"nome":"DAIANE SANTOS","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"HNQ6JMQM9J","ativo":"553","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"24052","data":"","valor":"","carregador":"554","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"BRENDA DEZIO","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"GR923WR4HR","ativo":"563","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"24052","data":"","valor":"","carregador":"564","garantia":"","old_user":"","formatado":"","cargo":""},
  {"nome":"MARCOS QUEIROZ","fabricante":"LENOVO","modelo":"THINKPAD T490 (2020)","sn":"PE06DC67","ativo":"21","status":"Não definido","avariado":"Não","obs":"victor deixou cachorro bater a pata, tela trocada","vendor":"LENOVO","nf":"203057","data":"10/16/2020","valor":"8.690,52","carregador":"22","garantia":"","old_user":"GABRIELE MENDES DOS SANTOS","formatado":"","cargo":""},
  {"nome":"VICTOR FELLYPE","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"GVW3CQ13QV","ativo":"558","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"24052","data":"","valor":"","carregador":"559","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"Mauricio Bueno","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"GPWRRY4WL3","ativo":"561","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"24052","data":"","valor":"","carregador":"560","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":"TI"},
  {"nome":"JULIA BRAGA PARENTE","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE07R42H","ativo":"1","status":"Não definido","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"9302","data":"8/16/2021","valor":"7.884,00","carregador":"2","garantia":"","old_user":"novo","formatado":"","cargo":""},
  {"nome":"SILVIO JUNIOR","fabricante":"DELL","modelo":"LATITUDE 5430","sn":"6HNRLY3","ativo":"282","status":"Não definido","avariado":"Não","obs":"","vendor":"DELL","nf":"5364235","data":"2023-03-07","valor":"7136.8","carregador":"283","garantia":"","old_user":"JULIANA PIGOZZI","formatado":"","cargo":""},
  {"nome":"KETLYN REIS","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE07R40Q","ativo":"394","status":"Não definido","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"9302","data":"8/16/2021","valor":"7.884,00","carregador":"57534","garantia":"","old_user":"JULIO HERMINIO BRESSAN MARTINS","formatado":"","cargo":""},
  {"nome":"LUCAS FUJITA","fabricante":"APPLE","modelo":"MACBOOK AIR M3","sn":"HL2TCFDWVY","ativo":"581","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"24052","data":"","valor":"","carregador":"582","garantia":"","old_user":"MICHAEL SILVA","formatado":"Sim","cargo":""},
  {"nome":"PAULO JEFFERSON OLIVEIRA","fabricante":"APPLE","modelo":"MACBOOK PRO 13","sn":"C02Z922VLVDL","ativo":"205","status":"Em uso","avariado":"Não","obs":"","vendor":"APPLE","nf":"4519852","data":"2019-10-09","valor":"","carregador":"156","garantia":"","old_user":"AUGUSTO CEZAR LEITE BATISTA PEREIRA","formatado":"Sim","cargo":""},
  {"nome":"CLAYGREGORI MATOS","fabricante":"APPLE","modelo":"MACBOOK PRO 13","sn":"C02G78QWML7H","ativo":"268","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"33831","data":"3/17/2022","valor":"","carregador":"269","garantia":"","old_user":"novo","formatado":"Sim","cargo":""},
  {"nome":"ARIANE DESTRO","fabricante":"DELL","modelo":"LATITUDE 5430","sn":"5HNRLY3","ativo":"664","status":"Não definido","avariado":"Não","obs":"","vendor":"DELL","nf":"5364235","data":"2023-03-07","valor":"7136.8","carregador":"","garantia":"","old_user":"Renan Maglione","formatado":"","cargo":""},
  {"nome":"DAIANE ALVES DOS SANTOS","fabricante":"APPLE","modelo":"MACBOOK PRO 13","sn":"C02G95WYML7H","ativo":"88","status":"Em uso","avariado":"Não","obs":"","vendor":"ALLIED","nf":"269163","data":"9/17/2021","valor":"","carregador":"89","garantia":"","old_user":"novo","formatado":"Sim","cargo":""},
  {"nome":"BRUNA SOARES","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE07R46X","ativo":"86","status":"Em uso","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"9302","data":"8/16/2021","valor":"7.884,00","carregador":"87","garantia":"","old_user":"WAGNER COSME","formatado":"Sim","cargo":""},
  {"nome":"SPARE T14 QUEIMOU","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE07R40B","ativo":"15","status":"Canibalização","avariado":"Sim","obs":"placa queimada, bateria reutilizada","vendor":"DIGITAL WORK","nf":"9302","data":"8/16/2021","valor":"7.884,00","carregador":"16","garantia":"","old_user":"WAGNER COSME DA SILVA","formatado":"","cargo":""},
  {"nome":"ALINE GARCIA","fabricante":"LENOVO","modelo":"THINKPAD T14","sn":"PE08S2HD","ativo":"178","status":"Não definido","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"12694","data":"4/26/2022","valor":"8900","carregador":"388","garantia":"","old_user":"EMILY CARVALHO","formatado":"","cargo":""},
  {"nome":"JESSICA CARVALHO","fabricante":"LENOVO","modelo":"THINKPAD T490 (2020)","sn":"PE06DC6N","ativo":"255","status":"Não definido","avariado":"Não","obs":"bateria ja foi substituida","vendor":"LENOVO","nf":"203057","data":"10/16/2020","valor":"8.690,52","carregador":"","garantia":"","old_user":"Vinicius Bravo","formatado":"","cargo":""},
  {"nome":"VICTOR BECCARE","fabricante":"APPLE","modelo":"MACBOOK PRO 13","sn":"C02FL5L3ML7H","ativo":"8","status":"Em uso","avariado":"Não","obs":"","vendor":"APPLE","nf":"194793","data":"10/06/2021","valor":"18.939,00","carregador":"7","garantia":"","old_user":"","formatado":"Sim","cargo":""},
  {"nome":"EDUARDO BALEOTTI","fabricante":"APPLE","modelo":"MACBOOK PRO 13 (2020)","sn":"C02CQ1QWML7H","ativo":"224","status":"Em uso","avariado":"Não","obs":"","vendor":"Fastshop","nf":"","data":"6/17/2020","valor":"","carregador":"83","garantia":"","old_user":"GIOVANA ARAUJO","formatado":"Sim","cargo":""},
  {"nome":"ANTONIO ROCHA","fabricante":"APPLE","modelo":"MACBOOK PRO M3","sn":"KYV63940XQ","ativo":"308","status":"Em uso","avariado":"Não","obs":"","vendor":"","nf":"","data":"","valor":"","carregador":"","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":"Diretor"},
  {"nome":"WAGNER COSME","fabricante":"LENOVO","modelo":"E14 ULTRA7","sn":"PE0EC51Z","ativo":"707","status":"Em uso","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"25945","data":"18/06/2025","valor":"7.199,00","carregador":"","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"Elaine Cabral","fabricante":"LENOVO","modelo":"E14 ULTRA7","sn":"PE0EC60Z","ativo":"709","status":"Em uso","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"25945","data":"18/06/2025","valor":"7.199,00","carregador":"","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"RAQUEL REIS","fabricante":"LENOVO","modelo":"E14 ULTRA5","sn":"PE0EC4XG","ativo":"608","status":"Em uso","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"25945","data":"18/06/2025","valor":"6.199,00","carregador":"","garantia":"","old_user":"MARCOS CANDIDO","formatado":"Sim","cargo":""},
  {"nome":"Martha Pelussi","fabricante":"LENOVO","modelo":"E14 ULTRA5","sn":"PE0EC4QN","ativo":"660","status":"Em uso","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"25945","data":"18/06/2025","valor":"6.199,00","carregador":"","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"BIANCA GALLI","fabricante":"LENOVO","modelo":"E14 ULTRA5","sn":"PE0EC4P9","ativo":"601","status":"Em uso","avariado":"Não","obs":"","vendor":"DIGITAL WORK","nf":"25945","data":"18/06/2025","valor":"6.199,00","carregador":"","garantia":"","old_user":"IGOR TRINDADE","formatado":"Sim","cargo":""},
  {"nome":"JAIR RANGEL","fabricante":"APPLE","modelo":"MACBOOK AIR M4","sn":"L4RP4TQJFT","ativo":"695","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"478054","data":"2025-03-11","valor":"12.799","carregador":"696","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"PAULO OLIVEIRA","fabricante":"APPLE","modelo":"MACBOOK AIR M4","sn":"KW4C30WDF2","ativo":"697","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"478054","data":"2025-03-11","valor":"12.799","carregador":"698","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"BEATRIZ CUNHA","fabricante":"APPLE","modelo":"MACBOOK AIR M4","sn":"HVH0QXQDKV","ativo":"613","status":"Em uso","avariado":"Não","obs":"","vendor":"INGRAM","nf":"478054","data":"2025-03-11","valor":"12.799","carregador":"612","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
  {"nome":"SPARE M4 620","fabricante":"APPLE","modelo":"MACBOOK AIR M4","sn":"CQWD1F2XW7","ativo":"620","status":"Estoque","avariado":"Não","obs":"","vendor":"INGRAM","nf":"478054","data":"2025-03-11","valor":"12.799","carregador":"621","garantia":"","old_user":"JAIME JACOBSON","formatado":"Sim","cargo":""},
  {"nome":"ANDRE BRANDO","fabricante":"APPLE","modelo":"MACBOOK AIR M4","sn":"JW4PFGX34D","ativo":"622","status":"Não definido","avariado":"Não","obs":"","vendor":"INGRAM","nf":"478054","data":"2025-03-11","valor":"12.799","carregador":"","garantia":"","old_user":"NOVO","formatado":"Sim","cargo":""},
];
